BloggerBlogBundle_homepage:
    path:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET




BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET